[build]
  cmd        = "go build -o ./tmp/allium-node ./cmd/allium-node"
  bin        = "./tmp/allium-node"
  full_bin   = "./tmp/allium-node --daemon-mode"
  include_ext = ["go"]
  exclude_dir = ["tmp", "build", "ui", "vendor"]
  delay      = 500

[log]
  color = true
